package main

// The countries the user can choose (ISO 3166 codes, as RIPE NCC uses them
// for every regional registry). Names from the Unicode CLDR.

type Country struct{ Code, EN, FA string }

var countries = []Country{
	{"AD", "Andorra", "آندورا"},
	{"AE", "United Arab Emirates", "امارات متحدهٔ عربی"},
	{"AF", "Afghanistan", "افغانستان"},
	{"AG", "Antigua & Barbuda", "آنتیگوا و باربودا"},
	{"AI", "Anguilla", "آنگویلا"},
	{"AL", "Albania", "آلبانی"},
	{"AM", "Armenia", "ارمنستان"},
	{"AO", "Angola", "آنگولا"},
	{"AQ", "Antarctica", "جنوبگان"},
	{"AR", "Argentina", "آرژانتین"},
	{"AS", "American Samoa", "ساموآی امریکا"},
	{"AT", "Austria", "اتریش"},
	{"AU", "Australia", "استرالیا"},
	{"AW", "Aruba", "آروبا"},
	{"AX", "Aland Islands", "جزایر آلاند"},
	{"AZ", "Azerbaijan", "جمهوری آذربایجان"},
	{"BA", "Bosnia & Herzegovina", "بوسنی و هرزگوین"},
	{"BB", "Barbados", "باربادوس"},
	{"BD", "Bangladesh", "بنگلادش"},
	{"BE", "Belgium", "بلژیک"},
	{"BF", "Burkina Faso", "بورکینافاسو"},
	{"BG", "Bulgaria", "بلغارستان"},
	{"BH", "Bahrain", "بحرین"},
	{"BI", "Burundi", "بوروندی"},
	{"BJ", "Benin", "بنین"},
	{"BL", "Saint Barthelemy", "سن بارتلمی"},
	{"BM", "Bermuda", "برمودا"},
	{"BN", "Brunei", "برونئی"},
	{"BO", "Bolivia", "بولیوی"},
	{"BQ", "Caribbean Netherlands", "جزایر کارائیب هلند"},
	{"BR", "Brazil", "برزیل"},
	{"BS", "Bahamas", "باهاما"},
	{"BT", "Bhutan", "بوتان"},
	{"BV", "Bouvet Island", "جزیرهٔ بووه"},
	{"BW", "Botswana", "بوتسوانا"},
	{"BY", "Belarus", "بلاروس"},
	{"BZ", "Belize", "بلیز"},
	{"CA", "Canada", "کانادا"},
	{"CC", "Cocos (Keeling) Islands", "جزایر کوکوس"},
	{"CD", "Congo (DRC)", "کنگو (کینشاسا)"},
	{"CF", "Central African Republic", "جمهوری افریقای مرکزی"},
	{"CG", "Congo (Republic)", "کنگو (برازاویل)"},
	{"CH", "Switzerland", "سوئیس"},
	{"CI", "Cote d'Ivoire", "ساحل عاج"},
	{"CK", "Cook Islands", "جزایر کوک"},
	{"CL", "Chile", "شیلی"},
	{"CM", "Cameroon", "کامرون"},
	{"CN", "China", "چین"},
	{"CO", "Colombia", "کلمبیا"},
	{"CR", "Costa Rica", "کاستاریکا"},
	{"CU", "Cuba", "کوبا"},
	{"CV", "Cape Verde", "کیپ‌ورد"},
	{"CW", "Curacao", "کوراسائو"},
	{"CX", "Christmas Island", "جزیرهٔ کریسمس"},
	{"CY", "Cyprus", "قبرس"},
	{"CZ", "Czechia", "چک"},
	{"DE", "Germany", "آلمان"},
	{"DJ", "Djibouti", "جیبوتی"},
	{"DK", "Denmark", "دانمارک"},
	{"DM", "Dominica", "دومینیکا"},
	{"DO", "Dominican Republic", "جمهوری دومینیکن"},
	{"DZ", "Algeria", "الجزایر"},
	{"EC", "Ecuador", "اکوادور"},
	{"EE", "Estonia", "استونی"},
	{"EG", "Egypt", "مصر"},
	{"EH", "Western Sahara", "صحرای غربی"},
	{"ER", "Eritrea", "اریتره"},
	{"ES", "Spain", "اسپانیا"},
	{"ET", "Ethiopia", "اتیوپی"},
	{"FI", "Finland", "فنلاند"},
	{"FJ", "Fiji", "فیجی"},
	{"FK", "Falkland Islands", "جزایر فالکلند"},
	{"FM", "Micronesia", "میکرونزی"},
	{"FO", "Faroe Islands", "جزایر فارو"},
	{"FR", "France", "فرانسه"},
	{"GA", "Gabon", "گابن"},
	{"GB", "United Kingdom", "بریتانیا"},
	{"GD", "Grenada", "گرنادا"},
	{"GE", "Georgia", "گرجستان"},
	{"GF", "French Guiana", "گویان فرانسه"},
	{"GG", "Guernsey", "گرنزی"},
	{"GH", "Ghana", "غنا"},
	{"GI", "Gibraltar", "جبل‌الطارق"},
	{"GL", "Greenland", "گرینلند"},
	{"GM", "Gambia", "گامبیا"},
	{"GN", "Guinea", "گینه"},
	{"GP", "Guadeloupe", "گوادلوپ"},
	{"GQ", "Equatorial Guinea", "گینهٔ استوایی"},
	{"GR", "Greece", "یونان"},
	{"GS", "South Georgia & South Sandwich Islands", "جورجیای جنوبی و جزایر ساندویچ جنوبی"},
	{"GT", "Guatemala", "گواتمالا"},
	{"GU", "Guam", "گوام"},
	{"GW", "Guinea-Bissau", "گینهٔ بیسائو"},
	{"GY", "Guyana", "گویان"},
	{"HK", "Hong Kong", "هنگ‌کنگ"},
	{"HM", "Heard & McDonald Islands", "هرد و جزایر مک‌دونالد"},
	{"HN", "Honduras", "هندوراس"},
	{"HR", "Croatia", "کرواسی"},
	{"HT", "Haiti", "هائیتی"},
	{"HU", "Hungary", "مجارستان"},
	{"ID", "Indonesia", "اندونزی"},
	{"IE", "Ireland", "ایرلند"},
	{"IL", "Israel", "اسرائیل"},
	{"IM", "Isle of Man", "جزیرهٔ من"},
	{"IN", "India", "هند"},
	{"IO", "British Indian Ocean Territory", "قلمرو بریتانیا در اقیانوس هند"},
	{"IQ", "Iraq", "عراق"},
	{"IR", "Iran", "ایران"},
	{"IS", "Iceland", "ایسلند"},
	{"IT", "Italy", "ایتالیا"},
	{"JE", "Jersey", "جرزی"},
	{"JM", "Jamaica", "جامائیکا"},
	{"JO", "Jordan", "اردن"},
	{"JP", "Japan", "ژاپن"},
	{"KE", "Kenya", "کنیا"},
	{"KG", "Kyrgyzstan", "قرقیزستان"},
	{"KH", "Cambodia", "کامبوج"},
	{"KI", "Kiribati", "کیریباتی"},
	{"KM", "Comoros", "کومور"},
	{"KN", "St. Kitts & Nevis", "سنت کیتس و نویس"},
	{"KP", "North Korea", "کرهٔ شمالی"},
	{"KR", "South Korea", "کرهٔ جنوبی"},
	{"KW", "Kuwait", "کویت"},
	{"KY", "Cayman Islands", "جزایر کِیمن"},
	{"KZ", "Kazakhstan", "قزاقستان"},
	{"LA", "Laos", "لائوس"},
	{"LB", "Lebanon", "لبنان"},
	{"LC", "St. Lucia", "سنت لوسیا"},
	{"LI", "Liechtenstein", "لیختن‌اشتاین"},
	{"LK", "Sri Lanka", "سری‌لانکا"},
	{"LR", "Liberia", "لیبریا"},
	{"LS", "Lesotho", "لسوتو"},
	{"LT", "Lithuania", "لیتوانی"},
	{"LU", "Luxembourg", "لوکزامبورگ"},
	{"LV", "Latvia", "لتونی"},
	{"LY", "Libya", "لیبی"},
	{"MA", "Morocco", "مراکش"},
	{"MC", "Monaco", "موناکو"},
	{"MD", "Moldova", "مولداوی"},
	{"ME", "Montenegro", "مونته‌نگرو"},
	{"MF", "St. Martin", "سنت مارتین"},
	{"MG", "Madagascar", "ماداگاسکار"},
	{"MH", "Marshall Islands", "جزایر مارشال"},
	{"MK", "North Macedonia", "مقدونیهٔ شمالی"},
	{"ML", "Mali", "مالی"},
	{"MM", "Myanmar", "میانمار"},
	{"MN", "Mongolia", "مغولستان"},
	{"MO", "Macao", "ماکائو"},
	{"MP", "Northern Mariana Islands", "جزایر ماریانای شمالی"},
	{"MQ", "Martinique", "مارتینیک"},
	{"MR", "Mauritania", "موریتانی"},
	{"MS", "Montserrat", "مونت‌سرات"},
	{"MT", "Malta", "مالت"},
	{"MU", "Mauritius", "موریس"},
	{"MV", "Maldives", "مالدیو"},
	{"MW", "Malawi", "مالاوی"},
	{"MX", "Mexico", "مکزیک"},
	{"MY", "Malaysia", "مالزی"},
	{"MZ", "Mozambique", "موزامبیک"},
	{"NA", "Namibia", "نامیبیا"},
	{"NC", "New Caledonia", "کالدونیای جدید"},
	{"NE", "Niger", "نیجر"},
	{"NF", "Norfolk Island", "جزیرهٔ نورفولک"},
	{"NG", "Nigeria", "نیجریه"},
	{"NI", "Nicaragua", "نیکاراگوئه"},
	{"NL", "Netherlands", "هلند"},
	{"NO", "Norway", "نروژ"},
	{"NP", "Nepal", "نپال"},
	{"NR", "Nauru", "نائورو"},
	{"NU", "Niue", "نیوئه"},
	{"NZ", "New Zealand", "نیوزیلند"},
	{"OM", "Oman", "عمان"},
	{"PA", "Panama", "پاناما"},
	{"PE", "Peru", "پرو"},
	{"PF", "French Polynesia", "پلی‌نزی فرانسه"},
	{"PG", "Papua New Guinea", "پاپوا گینهٔ نو"},
	{"PH", "Philippines", "فیلیپین"},
	{"PK", "Pakistan", "پاکستان"},
	{"PL", "Poland", "لهستان"},
	{"PM", "St. Pierre & Miquelon", "سن پیر و میکلن"},
	{"PN", "Pitcairn Islands", "جزایر پیت‌کرن"},
	{"PR", "Puerto Rico", "پورتوریکو"},
	{"PS", "Palestine", "فلسطین"},
	{"PT", "Portugal", "پرتغال"},
	{"PW", "Palau", "پالائو"},
	{"PY", "Paraguay", "پاراگوئه"},
	{"QA", "Qatar", "قطر"},
	{"RE", "Reunion", "رئونیون"},
	{"RO", "Romania", "رومانی"},
	{"RS", "Serbia", "صربستان"},
	{"RU", "Russia", "روسیه"},
	{"RW", "Rwanda", "رواندا"},
	{"SA", "Saudi Arabia", "عربستان سعودی"},
	{"SB", "Solomon Islands", "جزایر سلیمان"},
	{"SC", "Seychelles", "سیشل"},
	{"SD", "Sudan", "سودان"},
	{"SE", "Sweden", "سوئد"},
	{"SG", "Singapore", "سنگاپور"},
	{"SH", "St. Helena", "سنت هلن"},
	{"SI", "Slovenia", "اسلوونی"},
	{"SJ", "Svalbard & Jan Mayen", "سوالبارد و یان ماین"},
	{"SK", "Slovakia", "اسلواکی"},
	{"SL", "Sierra Leone", "سیرالئون"},
	{"SM", "San Marino", "سان‌مارینو"},
	{"SN", "Senegal", "سنگال"},
	{"SO", "Somalia", "سومالی"},
	{"SR", "Suriname", "سورینام"},
	{"SS", "South Sudan", "سودان جنوبی"},
	{"ST", "Sao Tome and Principe", "سائوتومه و پرینسیپ"},
	{"SV", "El Salvador", "السالوادور"},
	{"SX", "Sint Maarten", "سنت مارتن"},
	{"SY", "Syria", "سوریه"},
	{"SZ", "Eswatini", "اسواتینی"},
	{"TC", "Turks & Caicos Islands", "جزایر تورکس و کایکوس"},
	{"TD", "Chad", "چاد"},
	{"TF", "French Southern Territories", "سرزمین‌های جنوبی فرانسه"},
	{"TG", "Togo", "توگو"},
	{"TH", "Thailand", "تایلند"},
	{"TJ", "Tajikistan", "تاجیکستان"},
	{"TK", "Tokelau", "توکلائو"},
	{"TL", "Timor-Leste", "تیمور-لسته"},
	{"TM", "Turkmenistan", "ترکمنستان"},
	{"TN", "Tunisia", "تونس"},
	{"TO", "Tonga", "تونگا"},
	{"TR", "Türkiye", "ترکیه"},
	{"TT", "Trinidad & Tobago", "ترینیداد و توباگو"},
	{"TV", "Tuvalu", "تووالو"},
	{"TW", "Taiwan", "تایوان"},
	{"TZ", "Tanzania", "تانزانیا"},
	{"UA", "Ukraine", "اوکراین"},
	{"UG", "Uganda", "اوگاندا"},
	{"UM", "U.S. Outlying Islands", "جزایر دورافتادهٔ ایالات متحده"},
	{"US", "United States", "ایالات متحده"},
	{"UY", "Uruguay", "اروگوئه"},
	{"UZ", "Uzbekistan", "ازبکستان"},
	{"VA", "Vatican City", "واتیکان"},
	{"VC", "St. Vincent & Grenadines", "سنت وینسنت و گرنادین"},
	{"VE", "Venezuela", "ونزوئلا"},
	{"VG", "British Virgin Islands", "جزایر ویرجین بریتانیا"},
	{"VI", "U.S. Virgin Islands", "جزایر ویرجین ایالات متحده"},
	{"VN", "Vietnam", "ویتنام"},
	{"VU", "Vanuatu", "وانواتو"},
	{"WF", "Wallis & Futuna", "والیس و فوتونا"},
	{"WS", "Samoa", "ساموآ"},
	{"XK", "Kosovo", "کوزوو"},
	{"YE", "Yemen", "یمن"},
	{"YT", "Mayotte", "مایوت"},
	{"ZA", "South Africa", "افریقای جنوبی"},
	{"ZM", "Zambia", "زامبیا"},
	{"ZW", "Zimbabwe", "زیمبابوه"},
}
